#!/bin/bash

# Autoriser le trafic SSH
sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT

# Autoriser le trafic HTTP (port 80) et HTTPS (port 443) pour Apache2
sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 443 -j ACCEPT
